name: Test, Build and Release apk
on:
  push:
    tags:
      - "DEV*"
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.4'
    - run: flutter pub get
    - run: flutter pub run build_runner build --delete-conflicting-outputs
    # - run: flutter test
    - run: flutter build apk --flavor develop
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/develop/release/*.apk"
        token: ${{ secrets.TOKEN }}
